name: 'Build AUR package & push to the AUR'
description: 'Build an AUR package, test it and optionally push to the AUR'
branding:
  icon: user-check
  color: gray-dark
inputs:
  additionalPackages:
    description: 'Space-separated list of additional packages to install'
    required: false
    default: ''
  pushToAur:
    description: 'Push changes to the AUR'
    required: false
    default: 'false'
  workdir:
    description: 'The directory to work in'
    required: false
    default: './'
runs:
  using: 'docker'
  image: 'Dockerfile'
outputs:
  aurPackageName:
    description: 'The AUR package name'
  aurUpdated:
    description: 'Boolean if the AUR package was updated'
  currentVersion:
    description: 'The current AUR version'
  latestVersion:
    description: 'The latest available version'
