name: 'Build AUR package & push to the AUR'
description: 'Build an AUR package, test it and optionally push to the AUR'
branding:
  icon: user-check
  color: gray-dark
inputs:
  workdir:
    description: 'The directory to work in'
    required: false
    default: './'
  push-to-aur:
    description: 'Push changes to the AUR'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.workdir }}
  env:
    PUSH_TO_AUR: ${{ inputs.push-to-aur }}
